name: Build (and Deploy)

on:
  push:
    branches: 
      - main
  pull_request:
  schedule:
    - cron:  '30 2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build with elm-pages
      run: npm run build --if-present

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
