name: Build (and Deploy)

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install xmllint
        run: sudo apt-get install -y dos2unix fd-find

      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: yarn

      # TODO: figure out if we can avoid this
      - name: dos2unix
        run: fdfind . node_modules/ -x dos2unix {}

      - name: Build with elm-pages
        run: yarn build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
